### ISSUE TITLE
SplineObject.split() should be generalized

### ISSUE THREAD

**Issue by VikingScientist** [sintefmath/Splipy#77]
Currently `split()` is a function in `Curve`, `Surface` and `Volume`. First try in generalizing it to `SplineObject` failed since it need to construct instances of `Curve`, which is not available from `SplineObject`. I think it should be possible, but couldn't get it working.

**Comment by TheBB** [comment]
I did something like this in the (old) version of the G2 reader. It basically looked up the correct subclass in `SplineObject.__subclasses__()` according to its intended pardim (which is still there), and hope that they all have constructors that work the same way (which they do).
